kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-combined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-combined
  template:
    metadata:
      labels:
        app: app-combined
    spec:
      containers:
        - name: app1
          image: jp.icr.io/cti-roks-training/cicd-app1:latest  # app1のパイプラインで更新される
          ports:
            - name: http-app1
              containerPort: 8081
              protocol: TCP
        - name: app2
          image: jp.icr.io/cti-roks-training/cicd-app2:latest  # app2のパイプラインで更新される
          ports:
            - name: http-app2
              containerPort: 8089
              protocol: TCP
      imagePullSecrets:
        - name: all-icr-io
---
kind: Service
apiVersion: v1
metadata:
  name: app-combined
spec:
  ports:
    - name: http-app1
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: http-app2
      port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: app-combined
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app1
spec:
  to:
    kind: Service
    name: app-combined
  tls:
    termination: edge
  port:
    targetPort: http-app1
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app2
spec:
  to:
    kind: Service
    name: app-combined
  tls:
    termination: edge
  port:
    targetPort: http-app2

